### ISSUE TITLE
Question: Could you elaborate which bug needs rpcbind to run on nfsv4?

### ISSUE THREAD

**Issue by Cyber1000** [sjiveson/nfs-server-alpine#18]
Hi,

Thanks for this Dockerfile! Works fine, I'm just curious if you could provide a link to the bug, is it a bug in nfs-utils? It seems still to exist (uncomment the rpcbind and it didn't work as expected)

Thanks!

**Comment by sjiveson** [comment]
The best I have is this: https://www.spinics.net/lists/linux-nfs/msg59728.html as detailed in this issue: https://github.com/sjiveson/nfs-server-alpine/issues/4. Its quite the rabbit hole.

From the end of the thread: "Starting nfsd tries to register with
rpcbind (even for v4-only) and (due to the bug) it takes 3 minutes to
timeout."

**Comment by Cyber1000** [comment]
Sorry for my late response and thanks for your answer!

**Comment by sjiveson** [comment]
No worries and you're welcome.
